FROM nginxinc/nginx-unprivileged:alpine

COPY build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY docker-entrypoint.sh /docker-entrypoint.sh

USER root
RUN chmod +x /docker-entrypoint.sh
USER 1001

EXPOSE 8080

ENTRYPOINT ["/docker-entrypoint.sh"]
