---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer-analyst  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: '["mongodb-mcp"]'
  labels:
    app: customer-analyst
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: customer-analyst
    app.kubernetes.io/part-of: simon-casino-agents
    app.openshift.io/runtime: python
    component: agent
    kagenti.io/framework: Python
    kagenti.io/type: agent
    protocol.kagenti.io/a2a: ''
    kagenti.io/workload-type: deployment
    kagenti.io/inject: disabled # Enable to test AuthBridge
    kagenti.io/spire: disabled # authbridge-config SPIRE_ENABLED=False
  name: customer-analyst
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: customer-analyst
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: 'true'
        sidecar.opentelemetry.io/inject: app-sidecar
      labels:
        app: customer-analyst
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: customer-analyst
        app.kubernetes.io/part-of: simon-casino-agents
        app.openshift.io/runtime: python
        component: agent
        kagenti.io/inject: disabled # Enable to test AuthBridge
        kagenti.io/spire: disabled # authbridge-config SPIRE_ENABLED=False
        kagenti.io/type: agent
        kagenti.io/workload-type: deployment
        kagenti.io/framework: Python
        protocol.kagenti.io/a2a: ''
    spec:
      serviceAccount: customer-analyst
      containers:
      - envFrom:
        - configMapRef:
            name: marketing-assistant-config
        - secretRef:
            name: marketing-assistant-secrets
        image: quay.io/rh-ee-dayeo/marketing-assistant:customer-analyst
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 30
        name: agent
        ports:
        - containerPort: 8082
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: customer-analyst
spec:
  ports:
  - name: a2a
    port: 8080
    targetPort: 8082
  - name: original
    port: 8082
    targetPort: 8082
  selector:
    app: customer-analyst
