apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
    component: ui
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: 'true'
        sidecar.opentelemetry.io/inject: app-sidecar
      labels:
        app: frontend
        component: ui
    spec:
      containers:
      - image: quay.io/rh-ee-dayeo/marketing-assistant:frontend
        imagePullPolicy: Always
        name: frontend
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 25m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: frontend
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/timeout: 300s
  name: marketing-assistant-v2
spec:
  port:
    targetPort: 8080
  tls:
    termination: edge
  to:
    kind: Service
    name: frontend
