apiVersion: v1
kind: Service
metadata:
  name: marketing-assistant
  namespace: 0-marketing-assistant-demo
  labels:
    app: marketing-assistant
spec:
  selector:
    app: marketing-assistant
  ports:
  - name: http
    port: 8501
    targetPort: 8501
    protocol: TCP
  type: ClusterIP
