apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb-mcp
    app.kubernetes.io/name: mongodb-mcp
    component: mcp
    kagenti.io/transport: streamable_http
    kagenti.io/type: tool
    protocol.kagenti.io/mcp: ''
  name: mongodb-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-mcp
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: 'true'
        sidecar.opentelemetry.io/inject: app-sidecar
      labels:
        app: mongodb-mcp
        app.kubernetes.io/name: mongodb-mcp
        component: mcp
        kagenti.io/transport: streamable_http
        kagenti.io/type: tool
        protocol.kagenti.io/mcp: ''
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: marketing-assistant-config
        - secretRef:
            name: marketing-assistant-secrets
        image: quay.io/rh-ee-dayeo/marketing-assistant:mongodb-mcp
        imagePullPolicy: Always
        name: mcp
        ports:
        - containerPort: 8090
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-mcp
spec:
  ports:
  - port: 8090
    targetPort: 8090
  selector:
    app: mongodb-mcp
